language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - carnell28@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: E6WqUsvNBaznI6xiaDLzBVLr7pKGqR3uGOjBXqT5m6snZnQmH7awu364aHXgE5wte7kODIbtIhWOBFUxZqdFT6UUF/sTGrBEfVbK7H4cFNconiSoY9TJU6lll4MK/KMNHKCew4WfCDCTDefCuN4fVbMmb+hKHTGYNMo5IyzYFrpqitdt1Q3uNbu0A25tyAKluZ5eTMbO5ZG76B2eX5Pvge6h3Y0qEsCY+1vP7xcSBIEJYVw+PMfvp7DDgwkj4oAPu0wEelaxLfeCUDfkPRBAnCauyKfg1Ida1/aIieBd2xVkv+Ypm0lYnoMV/xlvuoZY6so4W7Ii3SJC7LGYVDtvcDSUY8yZVhNx8Lyf0G+PdjqoJcAkR670hwpDYAw6oe7neC4nRu+P60Z9MORe7rFSVDum0N/HZgAzDIOroZg4o00lqlH9GC/2OahLPxiq3cCl8i6lRi63m2aKHr/DNaPQ3312zoHA3G8TZYS1ZvfSLIEfCAOI4Ywz5N2CrE1vXbJX4nA/q1+R5tUwNKfB/KGC9hqHzuosBA5O1lQYJcTPLOMEH3qH1deen3T4KkjAWDhxZE93ovfmXUmZz3kMtkWXr3yEwwWM6L49QMPF0Iv+/eXOWnjYexJ0YU5hljgG96mBNhiLURRg/xDI6BsJLKBEb2fNGfp8k1crTyv7dVvjYvo=
  - secure: j97NlFyjfMEA1CDh1uPXpksrp7udS57/0DTIsIXRLUNXvn203Skm9DvUqp1wNhFSfBAhSM0xE7rsWiy23goVL8z3+pxW4DQxzi9THzB+Z76/eHr6gGfboYAI7xqxxweC89y52B3h9y3E+smFRW4HZeS4LC+nw/tXo0VQh58fbE4Ydqx0JLXEJYx0PpJ1eYEfa3U0D9OlB+c4p+KJcer3ufvnAtdOPpsnjySlzzd9cg/3H2Kgt3P2Axvk7x+nFAYlE2Ov02aO8n00MhXI1R9GkImN1wl8XCcXS7gZOXeR1Xd6WPyY5wHOiOUPZe5+NnTMNLWIWm9rfY3Tj7YGvq41JoWbP348PELaqzAb4bn6zYhjR7IMZLmBroQ3ndDNk9Ugu0TOufQIXZOEQvhcdPW80T4sVhJBprxMRpji3wp2nfk5AZ6uaW1ppbeKTCbXSNGUMY8syzcuzakNOHsw19yJDJ2bRl/6VJEV7xaSKmUYFCkGBsuUeB7deQWYzV04oC2RU4ZMXaz/l0oUy02HigPfWpuHcfuxl1rKQpkgi1HysiecQpPX+qGxnPuIkhTYqRYFTnNtaEFHgnnWdaAAHqj+7BsLECTnu83PB8eIOXu1urBHxrxFgG5Ghjv8dN14GhXTiXWmNIp0C9AwLIT4KHrUPT+x5F2Dqtb07Qmlnm1/XD0=
  - secure: km8ABs12DHC1juDJ1W6W1ekvo8E1pNxyySep2rFWsB1BLWQdK6vWNUi0EqcQVibRa/WEmSlHFZCfplkzK5ON3c1UbNMnqHkh3wNArDr8AcnaI7xRwGFxVIJtPGZVfQtma06QeXyE54pggjHMF9i9gGrNxyBIduEtX9ao1NIaUudnQiDPXAxMf9S5yrQarWnUUoNaJGU6KhY703LI5P7+znRn+GQ170J+WQdxloivfKqnrVASCHMQbkxi+KBuXhxCsRHcw/NkE9oKGlbG50UdR0LpSe4YJiuBuOXzJX2NwK0b8ycvovCalmNcqivRgNxaICiQ7wCvhxkxoP1+7zdNjGdjERIOPzGiT68r2qh47D9SDHgipjwX9IGtlXwHBgWiNLcRs+NbhJeuB5enKcSXH1+MrpERVBoO/vBWVX59iXobaA9XC9YgyYOOmBHkX7Ajk/2CUA/ADqKpeAbIBW2lpUft2Ni+5bWkjDVe7DetjwSYU/Gj6FRFtU3jsMTNitSmnbK6e/5DcPc3odxwsLKUgZiXU8RahiYIkesCm042Uu+sdcJ7SvxFGF6EkJPbtMxWuLi+Nza6c+uuKSQuOOGyKTTUmQxNf+BZIchdZM5bWOr6aH2ISzoAl44Of/OlkXrZmhm1QS+OkIN8fbivkXxWhQXJE7H2jeswV5WLfpZ7dgY=
  - secure: KOnFu91uxkxVpIgztouC6pHYYQBlbkifZ6vB3THU3RVh8DN5a2Q2jKJ9lqq5eDQn8csgNktDrAEXaSjVhychCXdAZelrk6LrTESeNG3pH60/fyxFvOuuJhE3lyTVMNL1uczJk4SShsUrJWKvO60GHh+ZGLDdcO/hq3K/RuQofMsmDeSiDlL/QW6eo2uoAD7JlSUvGdyJBpA0l0kMXvdLRhDoxQMjAUUKZQBt9wHPWiajqtDTlkLTV++mDsIzqZ+a98ZERtwoSSdUxWx4A4i3/UmhBL0YpHz0zCFD+3wYJODwTanQLpv2bbNBKyvRFvdSZqtzuTN/uIsxDlHUmtLGaO8QvASbTV29tNK5XFnUG80LpyLRysJVQPQqJhX4nH6zUrMuqc7mpF1XBcTTLnzhnmEYH0MuYSOdEQKAWfgXP2PmV6/F+lNcILgHv4DcX5yha0zCGnv3sKE3F3SeSYqzCtBrcISVLKyuPkO8qMdaGAeJPtdvknLrm4nNjXbBtEyrz145UkBh5uua/CXXrheDsKZudRRVjqTtbvYZ4nojqidb1H8a/v0yPixL+i/0z/RynRQ02h+VxESzA5Tv6CZOzjvkCPjY5DYq7KOPJNtoKbrD5+23Y5+UN6/Og6C8eef6mIirY+NE5qJxPUoNfA6FCFW0W1SSJpW4mme6e+a0n9w=
  - secure: IMo6+b8kxTXhavolsJQDwWPm5rKZfadUJu6U0sG/prFWi+wzMXln5XpASiiHomzDKQ3XYp6jrn8nU66R/H2Usv2Q9U/ikLevTXY4UGGxbzCU8j/yCOSzzZyD5K6XlvhFmqZClAuVCw8CRyzXMuBbq9dmZqOg+c5axlcLXH+W6raYWsS8t/kZuzVtp4thWX/7vOToxR7wZr8zQ+w/v8khXs9rs69fIv1YDPx+I8+spheFXGDsyI2bM+ZOxMbQxNHWtpsQpde6XIfaHo6cBUgx7C8Z8dr2/x3xGrDQ7SVzGw865fuEEaGs9wYa5C212NIPAeeA2ZIoob2qK2C+CA6N2wByZ/bGWXTTF0VzNIoiVZfZZuI60Jxk4wboCM5Ivdk2jxyEIFwPDfduarGIeSnooJo6dVj2jye/l46yF6Dzkwv9ZgpkMKch7tF/eftsY/BwTM8m0nKYcVbwpT5M9bmrQZCzrJfYqLJfASsM8B0mxkFD2Owtwswdw2C4MhtvcGwvOpMn4Td/sMv+QODNnEn9/yQX4iOAqtTU3m8VhqOOHqzPN/UcjW/Ro5vcDmY232zZljUYdcYyOrphheJJ/iMwk0YlLz+rIEATNSOSb9aD4hTMtinHMXxxe5FyZiZ7Upk2vnuMogjbQ0hvEWAkXYh2DRlKwiiNyPi0+MHWF5kdb60=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.215.193.139
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
# sh travis_scripts/trigger_platform_tests.sh
